apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch8
  name: elasticsearch8
  namespace: kube-middleware
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-9200
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: tcp-9300
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: elasticsearch8
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: es-cluster
  namespace: kube-middleware
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-9200
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: tcp-9300
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: elasticsearch8
  type: ClusterIP
status:
  loadBalancer: {}
